# Cycle between high and low quality shaders
g cycle-values glsl-shaders "~~/shaders/nnedi3-nns128-win8x4.hook" "~~/shaders/ArtCNN_C4F32.glsl" ""

# Force override subtitle styles
k cycle_values sub-ass-override "force" "no"
