# Video profile and output drivers
profile=high-quality
gpu-api=vulkan
vo=gpu-next

# Sets the strength of the antiring filter
scale-antiring=0.6

# Dither (this must be set to match your monitor's bit depth)
dither-depth=8

## Screenshot settings
screenshot-format=png
screenshot-dir="~/Pictures/mpv"
screenshot-template="%F-%p-%n"
screenshot-high-bit-depth=yes

# Language priority (add enm before eng for honorifics)
slang=eng,en,en-US,english-subs
alang=jpn,ja

# Subtitle style overrides
sub-ass-override=no
sub-ass-style-overrides=playresx=1920,playresy=1080
sub-font="Gandhi Sans"
sub-font-size=50
sub-color="#FFFFFF"
sub-margin-y=40
sub-border-size=2.4
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=0.75
sub-bold=yes
sub-ass-style-overrides=Kerning=yes

# Automatic profiles
[Crunchyroll]
profile-cond=filename:match("SubsPlease") or filename:match("Erai%-raws") or filename:match("HorribleSubs")
profile-restore=copy
sub-ass-use-video-data=aspect-ratio

[Simulcast]
profile-cond=(function(a) for b,c in ipairs(a) do if filename:match(c) then return true end end end)({"SubsPlease", "Erai%-raws", "Tsundere%-Raws", "%-VARYG", "HorribleSubs", "SubsPlus%+", "Yameii"})
profile-restore=copy
deband=yes
